### ISSUE TITLE
Not clearing default property keyword

### ISSUE THREAD

**Issue by tvercruysse** [kotfire/vscode-php-add-property#3] opened 2019-11-09 11:23 UTC
When enabling the choose visibility option it allows the user to choose between private, protected, public as intended.
However when i hit tab/enter to insert my selected keyword, it prepends my choice to the default private keyword ( like so: choose public, hit tab/enter will result in `publicprivate` ) 

This happens with or without vim-mode enabled.

Will debug more later to track down if it is interference with another extension.

Besides a few early quirks extension seems be solid tho, great work!

**Comment by kotfire** [comment] 2019-12-06 14:34
I could not reproduce this. Can you try disabling all other extensions first?

**Comment by kotfire** [comment] 2020-08-31 21:54
Without additional information, I'm unfortunately not able to resolve this issue. I'm going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information; I'll reopen it right away!
Thanks for your contribution

**Closed as completed by kotfire** 2020-08-31 21:54 UTC
Labels: not-reproducible
